version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: search_postgres
    environment:
      POSTGRES_USER: search
      POSTGRES_PASSWORD: search
      POSTGRES_DB: search_engine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
